### ISSUE TITLE
Secondaries slightly incorrect

### ISSUE THREAD

**Issue by zacmcnulty123** [disk5464/Randomized-Space-Marine-2-Missions#1]
As a player I would like the assault class to have the correct options. Vanguard and Sniper additionally have the plasma pistol which are not valid options. This ticket encompasses the work to correct these small discrepancies. This is done by editing the secondary class options to be aligned with the valid options within the class system of space marine 2.[

**Comment by disk5464** [comment]
Meged in with commit 482676c
